// <auto-generated />
using System;
using GamP_SCPeriop.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamP_SCPeriop.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519093813_AddedNotifications")]
    partial class AddedNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PathwayId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PathwayId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PathwayId = 2,
                            ProfessorId = 10,
                            ProgressPercentage = 80,
                            StudentId = 11
                        },
                        new
                        {
                            Id = 4,
                            EndDate = new DateTime(2026, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PathwayId = 1,
                            ProfessorId = 9,
                            ProgressPercentage = 5,
                            StudentId = 12
                        });
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PathwayId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PathwayId");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PathwayId = 1,
                            Title = "Módulo Teórico - Preparação"
                        },
                        new
                        {
                            Id = 2,
                            PathwayId = 1,
                            Title = "Módulo Prático - Bloco Operatório"
                        },
                        new
                        {
                            Id = 3,
                            PathwayId = 2,
                            Title = "Módulo Único - Fármacos"
                        });
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.ModuleComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("PdfFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("ModuleComponents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModuleId = 1,
                            PdfFilePath = "",
                            Stage = 1,
                            Status = 0,
                            Title = "Guia de Higienização"
                        },
                        new
                        {
                            Id = 2,
                            ModuleId = 2,
                            PdfFilePath = "",
                            Stage = 2,
                            Status = 0,
                            Title = "Checklist Cirúrgica"
                        },
                        new
                        {
                            Id = 3,
                            ModuleId = 1,
                            PdfFilePath = "https://example.com/manual.pdf",
                            Stage = 1,
                            Status = 0,
                            Title = "Manual de Acolhimento"
                        },
                        new
                        {
                            Id = 4,
                            ModuleId = 1,
                            PdfFilePath = "",
                            Stage = 2,
                            Status = 0,
                            Title = "Checklist de Segurança (OMS)"
                        },
                        new
                        {
                            Id = 5,
                            ModuleId = 2,
                            PdfFilePath = "",
                            Stage = 4,
                            Status = 0,
                            Title = "Preparação da Sala Operatória"
                        },
                        new
                        {
                            Id = 6,
                            ModuleId = 2,
                            PdfFilePath = "",
                            Stage = 5,
                            Status = 0,
                            Title = "Circulação na Sala"
                        },
                        new
                        {
                            Id = 7,
                            ModuleId = 3,
                            PdfFilePath = "https://example.com/farmacos.pdf",
                            Stage = 1,
                            Status = 0,
                            Title = "Tabela de Fármacos de Emergência"
                        },
                        new
                        {
                            Id = 8,
                            ModuleId = 3,
                            PdfFilePath = "",
                            Stage = 3,
                            Status = 0,
                            Title = "Preparação do Ventilação"
                        },
                        new
                        {
                            Id = 9,
                            ModuleId = 3,
                            PdfFilePath = "",
                            Stage = 5,
                            Status = 0,
                            Title = "Entubação Endotraqueal"
                        });
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Pathway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MinimumApprovalScore")
                        .HasColumnType("int");

                    b.Property<int>("MinimumPassScore")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pathways");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MinimumApprovalScore = 75,
                            MinimumPassScore = 50,
                            ProfessorId = 9,
                            Title = "Enfermagem Cirúrgica"
                        },
                        new
                        {
                            Id = 2,
                            MinimumApprovalScore = 80,
                            MinimumPassScore = 50,
                            ProfessorId = 10,
                            Title = "Anestesia Básica"
                        });
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            Email = "miguel@ipca.com",
                            FullName = "Miguel Teixeira",
                            Password = "123",
                            Role = 0,
                            University = "IPCA"
                        },
                        new
                        {
                            Id = 7,
                            Email = "a100@alunos.ipca.pt",
                            FullName = "Rúben Peixoto",
                            Password = "123",
                            Role = 1,
                            University = "IPCA"
                        },
                        new
                        {
                            Id = 8,
                            Email = "professorTeste@ipca.pt",
                            FullName = "Teste de nome",
                            Password = "123",
                            Role = 0,
                            University = "IPCA"
                        },
                        new
                        {
                            Id = 9,
                            Email = "armando.costa@hospital.pt",
                            FullName = "Dr. Armando Costa",
                            Password = "123",
                            Role = 0,
                            University = "Hospital Central"
                        },
                        new
                        {
                            Id = 10,
                            Email = "beatriz.sousa@hospital.pt",
                            FullName = "Enf. Beatriz Sousa",
                            Password = "123",
                            Role = 0,
                            University = "Hospital Central"
                        },
                        new
                        {
                            Id = 11,
                            Email = "a101@alunos.ipca.pt",
                            FullName = "Ana Silva",
                            Password = "123",
                            Role = 1,
                            University = "Universidade do Minho"
                        },
                        new
                        {
                            Id = 12,
                            Email = "a102@alunos.ipca.pt",
                            FullName = "Carlos Martins",
                            Password = "123",
                            Role = 1,
                            University = "Universidade do Porto"
                        });
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Notification", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.User", null)
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamP_SCPeriop.Shared.User", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Enrollment", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.Pathway", "Pathway")
                        .WithMany()
                        .HasForeignKey("PathwayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamP_SCPeriop.Shared.User", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamP_SCPeriop.Shared.User", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pathway");

                    b.Navigation("Professor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Module", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.Pathway", null)
                        .WithMany("Modules")
                        .HasForeignKey("PathwayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.ModuleComponent", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.Module", null)
                        .WithMany("Components")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Module", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Pathway", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.User", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
