// <auto-generated />
using System;
using GamP_SCPeriop.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamP_SCPeriop.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331155720_EnrollmentSupervisor")]
    partial class EnrollmentSupervisor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamP_SCPeriop.Shared.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PathwayId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PathwayId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PathwayId = 1,
                            ProfessorId = 6,
                            ProgressPercentage = 15,
                            StudentId = 7
                        });
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PathwayId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PathwayId");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PathwayId = 1,
                            Title = "Módulo Teórico - Preparação"
                        },
                        new
                        {
                            Id = 2,
                            PathwayId = 1,
                            Title = "Módulo Prático - Bloco Operatório"
                        },
                        new
                        {
                            Id = 3,
                            PathwayId = 2,
                            Title = "Módulo Único - Fármacos"
                        });
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.ModuleComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("PdfFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("ModuleComponents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModuleId = 1,
                            PdfFilePath = "",
                            Status = 0,
                            Title = "Guia de Higienização"
                        },
                        new
                        {
                            Id = 2,
                            ModuleId = 2,
                            PdfFilePath = "",
                            Status = 0,
                            Title = "Checklist Cirúrgica"
                        });
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Pathway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MinimumApprovalScore")
                        .HasColumnType("int");

                    b.Property<int>("MinimumPassScore")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pathways");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MinimumApprovalScore = 75,
                            MinimumPassScore = 50,
                            Title = "Enfermagem Cirúrgica"
                        },
                        new
                        {
                            Id = 2,
                            MinimumApprovalScore = 80,
                            MinimumPassScore = 50,
                            Title = "Anestesia Básica"
                        });
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            Email = "miguel@ipca.com",
                            FullName = "Miguel Teixeira",
                            Password = "123",
                            Role = 0,
                            University = "IPCA"
                        },
                        new
                        {
                            Id = 7,
                            Email = "a100@alunos.ipca.pt",
                            FullName = "Rúben Peixoto",
                            Password = "123",
                            Role = 1,
                            University = "IPCA"
                        },
                        new
                        {
                            Id = 8,
                            Email = "professorTeste@ipca.pt",
                            FullName = "Teste de nome",
                            Password = "123",
                            Role = 0,
                            University = "IPCA"
                        });
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Enrollment", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.Pathway", "Pathway")
                        .WithMany()
                        .HasForeignKey("PathwayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamP_SCPeriop.Shared.User", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamP_SCPeriop.Shared.User", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pathway");

                    b.Navigation("Professor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Module", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.Pathway", null)
                        .WithMany("Modules")
                        .HasForeignKey("PathwayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.ModuleComponent", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.Module", null)
                        .WithMany("Components")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Module", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Pathway", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.User", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
