// <auto-generated />
using System;
using GamP_SCPeriop.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamP_SCPeriop.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630111051_AddModuleStageTimeline")]
    partial class AddModuleStageTimeline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.ComponentEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModuleComponentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("ModuleComponentId");

                    b.ToTable("ComponentEvaluations");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PathwayId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PathwayId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PathwayId = 2,
                            ProfessorId = 10,
                            ProgressPercentage = 0,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 11
                        },
                        new
                        {
                            Id = 4,
                            EndDate = new DateTime(2026, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PathwayId = 1,
                            ProfessorId = 9,
                            ProgressPercentage = 0,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 12
                        });
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PathwayId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PathwayId");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PathwayId = 1,
                            Title = "Módulo Teórico - Preparação"
                        },
                        new
                        {
                            Id = 2,
                            PathwayId = 1,
                            Title = "Módulo Prático - Bloco Operatório"
                        },
                        new
                        {
                            Id = 3,
                            PathwayId = 2,
                            Title = "Módulo Único - Fármacos"
                        },
                        new
                        {
                            Id = 4,
                            PathwayId = 2,
                            Title = "UT1 - Introdução à Anestesia"
                        });
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.ModuleComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentComponentId")
                        .HasColumnType("int");

                    b.Property<string>("PdfFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("ParentComponentId");

                    b.ToTable("ModuleComponents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModuleId = 1,
                            PdfFilePath = "",
                            Stage = 1,
                            Title = "Guia de Higienização"
                        },
                        new
                        {
                            Id = 2,
                            ModuleId = 2,
                            PdfFilePath = "",
                            Stage = 2,
                            Title = "Checklist Cirúrgica"
                        },
                        new
                        {
                            Id = 3,
                            ModuleId = 1,
                            PdfFilePath = "https://example.com/manual.pdf",
                            Stage = 1,
                            Title = "Manual de Acolhimento"
                        },
                        new
                        {
                            Id = 4,
                            ModuleId = 1,
                            PdfFilePath = "",
                            Stage = 2,
                            Title = "Checklist de Segurança (OMS)"
                        },
                        new
                        {
                            Id = 5,
                            ModuleId = 2,
                            PdfFilePath = "",
                            Stage = 4,
                            Title = "Preparação da Sala Operatória"
                        },
                        new
                        {
                            Id = 6,
                            ModuleId = 2,
                            PdfFilePath = "",
                            Stage = 5,
                            Title = "Circulação na Sala"
                        },
                        new
                        {
                            Id = 7,
                            ModuleId = 3,
                            PdfFilePath = "https://example.com/farmacos.pdf",
                            Stage = 1,
                            Title = "Tabela de Fármacos de Emergência"
                        },
                        new
                        {
                            Id = 8,
                            ModuleId = 3,
                            PdfFilePath = "",
                            Stage = 3,
                            Title = "Preparação do Ventilação"
                        },
                        new
                        {
                            Id = 9,
                            ModuleId = 3,
                            PdfFilePath = "",
                            Stage = 5,
                            Title = "Entubação Endotraqueal"
                        },
                        new
                        {
                            Id = 10,
                            ModuleId = 4,
                            Stage = 2,
                            Title = "Demonstra conhecimento das Normas de prevenção da Infeção do Local Cirúrgico"
                        },
                        new
                        {
                            Id = 11,
                            ModuleId = 4,
                            Stage = 2,
                            Title = "Procede aos devidos registos clínicos informáticos no intraoperatório"
                        },
                        new
                        {
                            Id = 12,
                            ModuleId = 4,
                            Stage = 2,
                            Title = "Sclínico"
                        },
                        new
                        {
                            Id = 13,
                            ModuleId = 4,
                            ParentComponentId = 12,
                            Stage = 2,
                            Title = "Regista Diagnósticos de Enfermagem adequadamente"
                        },
                        new
                        {
                            Id = 14,
                            ModuleId = 4,
                            ParentComponentId = 12,
                            Stage = 2,
                            Title = "Regista Atitudes terapêuticas adequadamente"
                        },
                        new
                        {
                            Id = 15,
                            ModuleId = 4,
                            ParentComponentId = 12,
                            Stage = 2,
                            Title = "Regista SV (incluindo temperatura corporal) e Glicemia Capilar de acordo com as normas em vigor"
                        },
                        new
                        {
                            Id = 16,
                            ModuleId = 4,
                            Stage = 2,
                            Title = "Valida adequadamente a administração de medicação no sistema Ghaf;"
                        },
                        new
                        {
                            Id = 17,
                            ModuleId = 4,
                            Stage = 2,
                            Title = "Ghaf"
                        },
                        new
                        {
                            Id = 18,
                            ModuleId = 4,
                            ParentComponentId = 17,
                            Stage = 2,
                            Title = "Administração de Antibioterapia, de acordo com a norma em vigor"
                        },
                        new
                        {
                            Id = 19,
                            ModuleId = 4,
                            ParentComponentId = 17,
                            Stage = 2,
                            Title = "Efetua débitos ao armazém"
                        },
                        new
                        {
                            Id = 20,
                            ModuleId = 4,
                            ParentComponentId = 17,
                            Stage = 2,
                            Title = "Efetua devoluções ao armazém"
                        },
                        new
                        {
                            Id = 21,
                            ModuleId = 4,
                            ParentComponentId = 17,
                            Stage = 2,
                            Title = "Efetua pedidos de dietas para o utente e acompanhante (quando aplicável)"
                        },
                        new
                        {
                            Id = 22,
                            ModuleId = 4,
                            Stage = 2,
                            Title = "Regista adequadamente a administração de estupefacientes em folha própria (Mod.3)"
                        });
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Pathway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MinimumApprovalScore")
                        .HasColumnType("int");

                    b.Property<int>("MinimumPassScore")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pathways");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MinimumApprovalScore = 75,
                            MinimumPassScore = 50,
                            ProfessorId = 9,
                            Title = "Enfermagem Cirúrgica"
                        },
                        new
                        {
                            Id = 2,
                            MinimumApprovalScore = 80,
                            MinimumPassScore = 50,
                            ProfessorId = 10,
                            Title = "Anestesia Básica"
                        });
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            Email = "miguel@ipca.com",
                            FullName = "Miguel Teixeira",
                            Password = "123",
                            Role = 0,
                            University = "IPCA"
                        },
                        new
                        {
                            Id = 7,
                            Email = "a100@alunos.ipca.pt",
                            FullName = "Rúben Peixoto",
                            Password = "123",
                            Role = 1,
                            University = "IPCA"
                        },
                        new
                        {
                            Id = 8,
                            Email = "professorTeste@ipca.pt",
                            FullName = "Teste de nome",
                            Password = "123",
                            Role = 0,
                            University = "IPCA"
                        },
                        new
                        {
                            Id = 9,
                            Email = "armando.costa@hospital.pt",
                            FullName = "Dr. Armando Costa",
                            Password = "123",
                            Role = 0,
                            University = "Hospital Central"
                        },
                        new
                        {
                            Id = 10,
                            Email = "beatriz.sousa@hospital.pt",
                            FullName = "Enf. Beatriz Sousa",
                            Password = "123",
                            Role = 0,
                            University = "Hospital Central"
                        },
                        new
                        {
                            Id = 11,
                            Email = "a101@alunos.ipca.pt",
                            FullName = "Ana Silva",
                            Password = "123",
                            Role = 1,
                            University = "Universidade do Minho"
                        },
                        new
                        {
                            Id = 12,
                            Email = "a102@alunos.ipca.pt",
                            FullName = "Carlos Martins",
                            Password = "123",
                            Role = 1,
                            University = "Universidade do Porto"
                        });
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Entity.Model.ModuleStageTimeline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("ModuleStageTimelines");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.ComponentEvaluation", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.Data.Enrollment", "Enrollment")
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamP_SCPeriop.Shared.Data.ModuleComponent", "ModuleComponent")
                        .WithMany()
                        .HasForeignKey("ModuleComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("ModuleComponent");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Enrollment", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.Data.Pathway", "Pathway")
                        .WithMany()
                        .HasForeignKey("PathwayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamP_SCPeriop.Shared.Data.User", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamP_SCPeriop.Shared.Data.User", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pathway");

                    b.Navigation("Professor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Module", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.Data.Pathway", null)
                        .WithMany("Modules")
                        .HasForeignKey("PathwayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.ModuleComponent", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.Data.Module", "Module")
                        .WithMany("Components")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamP_SCPeriop.Shared.Data.ModuleComponent", "ParentComponent")
                        .WithMany("SubComponents")
                        .HasForeignKey("ParentComponentId");

                    b.Navigation("Module");

                    b.Navigation("ParentComponent");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Notification", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.Data.User", null)
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamP_SCPeriop.Shared.Data.User", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Entity.Model.ModuleStageTimeline", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.Data.Module", "Module")
                        .WithMany("StageTimelines")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Module", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("StageTimelines");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.ModuleComponent", b =>
                {
                    b.Navigation("SubComponents");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Pathway", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.User", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
