// <auto-generated />
using System;
using GamP_SCPeriop.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamP_SCPeriop.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728163049_AddedUserBadgeAndBadgeModels")]
    partial class AddedUserBadgeAndBadgeModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PathwayId")
                        .HasColumnType("int");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.Property<int>("TriggerType")
                        .HasColumnType("int");

                    b.Property<string>("TriggerValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.ComponentEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModuleComponentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("ModuleComponentId");

                    b.ToTable("ComponentEvaluations");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PathwayId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PathwayId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PathwayId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PathwayId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.ModuleComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentComponentId")
                        .HasColumnType("int");

                    b.Property<string>("PdfFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("ParentComponentId");

                    b.ToTable("ModuleComponents");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Pathway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MinimumApprovalScore")
                        .HasColumnType("int");

                    b.Property<int>("MinimumPassScore")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pathways");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Template.BadgeTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PathwayTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.Property<int>("TriggerType")
                        .HasColumnType("int");

                    b.Property<string>("TriggerValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BadgeTemplates");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Template.ComponentTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModuleTemplateId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentComponentTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("PdfFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleTemplateId");

                    b.HasIndex("ParentComponentTemplateId");

                    b.ToTable("ComponentTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModuleTemplateId = 1,
                            Stage = 1,
                            Title = "Guia de Higienização",
                            Weight = 50
                        },
                        new
                        {
                            Id = 3,
                            ModuleTemplateId = 1,
                            Stage = 1,
                            Title = "Manual de Acolhimento",
                            Weight = 50
                        },
                        new
                        {
                            Id = 2,
                            ModuleTemplateId = 2,
                            Stage = 2,
                            Title = "Checklist Cirúrgica",
                            Weight = 100
                        },
                        new
                        {
                            Id = 7,
                            ModuleTemplateId = 3,
                            Stage = 1,
                            Title = "Tabela de Fármacos de Emergência",
                            Weight = 100
                        },
                        new
                        {
                            Id = 10,
                            ModuleTemplateId = 4,
                            Stage = 2,
                            Title = "Demonstra conhecimento das Normas de prevenção",
                            Weight = 20
                        },
                        new
                        {
                            Id = 11,
                            ModuleTemplateId = 4,
                            Stage = 2,
                            Title = "Procede aos devidos registos clínicos",
                            Weight = 20
                        },
                        new
                        {
                            Id = 12,
                            ModuleTemplateId = 4,
                            Stage = 2,
                            Title = "Sclínico",
                            Weight = 30
                        },
                        new
                        {
                            Id = 13,
                            ModuleTemplateId = 4,
                            ParentComponentTemplateId = 12,
                            Stage = 2,
                            Title = "Regista Diagnósticos de Enfermagem",
                            Weight = 34
                        },
                        new
                        {
                            Id = 14,
                            ModuleTemplateId = 4,
                            ParentComponentTemplateId = 12,
                            Stage = 2,
                            Title = "Regista Atitudes terapêuticas",
                            Weight = 33
                        },
                        new
                        {
                            Id = 15,
                            ModuleTemplateId = 4,
                            ParentComponentTemplateId = 12,
                            Stage = 2,
                            Title = "Regista SV e Glicemia Capilar",
                            Weight = 33
                        },
                        new
                        {
                            Id = 17,
                            ModuleTemplateId = 4,
                            Stage = 2,
                            Title = "Ghaf",
                            Weight = 30
                        },
                        new
                        {
                            Id = 18,
                            ModuleTemplateId = 4,
                            ParentComponentTemplateId = 17,
                            Stage = 2,
                            Title = "Administração de Antibioterapia",
                            Weight = 25
                        },
                        new
                        {
                            Id = 19,
                            ModuleTemplateId = 4,
                            ParentComponentTemplateId = 17,
                            Stage = 2,
                            Title = "Efetua débitos ao armazém",
                            Weight = 25
                        },
                        new
                        {
                            Id = 20,
                            ModuleTemplateId = 4,
                            ParentComponentTemplateId = 17,
                            Stage = 2,
                            Title = "Efetua devoluções ao armazém",
                            Weight = 25
                        },
                        new
                        {
                            Id = 21,
                            ModuleTemplateId = 4,
                            ParentComponentTemplateId = 17,
                            Stage = 2,
                            Title = "Efetua pedidos de dietas",
                            Weight = 25
                        });
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Template.ModuleTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PathwayTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PathwayTemplateId");

                    b.ToTable("ModuleTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PathwayTemplateId = 1,
                            Title = "Módulo Teórico - Preparação"
                        },
                        new
                        {
                            Id = 2,
                            PathwayTemplateId = 1,
                            Title = "Módulo Prático - Bloco Operatório"
                        },
                        new
                        {
                            Id = 3,
                            PathwayTemplateId = 2,
                            Title = "Módulo Único - Fármacos"
                        },
                        new
                        {
                            Id = 4,
                            PathwayTemplateId = 2,
                            Title = "UT1 - Introdução à Anestesia"
                        });
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Template.PathwayTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdminBase")
                        .HasColumnType("bit");

                    b.Property<int>("MinimumApprovalScore")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorOwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PathwayTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Molde base que inclui preparação teórica e observação prática.",
                            IsAdminBase = true,
                            MinimumApprovalScore = 100,
                            Title = "Molde Standard - Bloco Operatório"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Focado exclusivamente em procedimentos de anestesiologia.",
                            IsAdminBase = true,
                            MinimumApprovalScore = 100,
                            Title = "Molde Avançado - Anestesia"
                        });
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.UserBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Entity.Model.ModuleStageTimeline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("ModuleStageTimelines");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.ComponentEvaluation", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.Data.Enrollment", "Enrollment")
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamP_SCPeriop.Shared.Data.ModuleComponent", "ModuleComponent")
                        .WithMany()
                        .HasForeignKey("ModuleComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("ModuleComponent");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Enrollment", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.Data.Pathway", "Pathway")
                        .WithMany()
                        .HasForeignKey("PathwayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamP_SCPeriop.Shared.Data.User", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamP_SCPeriop.Shared.Data.User", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pathway");

                    b.Navigation("Professor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Module", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.Data.Pathway", null)
                        .WithMany("Modules")
                        .HasForeignKey("PathwayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.ModuleComponent", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.Data.Module", "Module")
                        .WithMany("Components")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamP_SCPeriop.Shared.Data.ModuleComponent", "ParentComponent")
                        .WithMany("SubComponents")
                        .HasForeignKey("ParentComponentId");

                    b.Navigation("Module");

                    b.Navigation("ParentComponent");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Notification", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.Data.User", null)
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamP_SCPeriop.Shared.Data.User", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Template.ComponentTemplate", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.Data.Template.ModuleTemplate", "ModuleTemplate")
                        .WithMany("ComponentTemplates")
                        .HasForeignKey("ModuleTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamP_SCPeriop.Shared.Data.Template.ComponentTemplate", "ParentComponentTemplate")
                        .WithMany("SubComponents")
                        .HasForeignKey("ParentComponentTemplateId");

                    b.Navigation("ModuleTemplate");

                    b.Navigation("ParentComponentTemplate");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Template.ModuleTemplate", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.Data.Template.PathwayTemplate", "PathwayTemplate")
                        .WithMany("ModuleTemplates")
                        .HasForeignKey("PathwayTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PathwayTemplate");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.UserBadge", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.Data.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Entity.Model.ModuleStageTimeline", b =>
                {
                    b.HasOne("GamP_SCPeriop.Shared.Data.Module", "Module")
                        .WithMany("StageTimelines")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Module", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("StageTimelines");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.ModuleComponent", b =>
                {
                    b.Navigation("SubComponents");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Pathway", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Template.ComponentTemplate", b =>
                {
                    b.Navigation("SubComponents");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Template.ModuleTemplate", b =>
                {
                    b.Navigation("ComponentTemplates");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.Template.PathwayTemplate", b =>
                {
                    b.Navigation("ModuleTemplates");
                });

            modelBuilder.Entity("GamP_SCPeriop.Shared.Data.User", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
